import {
  registerNuxtUiGlobals,
  nuxtUiComponentDefinitions,
} from "json-render-nuxt-ui";
import {
  UAccordion,
  UAlert,
  UAvatar,
  UBadge,
  UCarousel,
  UCard,
  UCollapsible,
  UButton,
  UDrawer,
  UDropdownMenu,
  UInput,
  UPagination,
  UPopover,
  UProgress,
  URadioGroup,
  USelect,
  USkeleton,
  USlider,
  UTable,
  UTabs,
  UCheckbox,
  UTextarea,
  UTooltip,
  USwitch,
  UModal,
} from "#components";

export default defineNuxtPlugin((nuxtApp) => {
  registerNuxtUiGlobals(
    nuxtApp,
    {
      UAccordion,
      UAlert,
      UAvatar,
      UBadge,
      UCarousel,
      UCard,
      UCollapsible,
      UButton,
      UDrawer,
      UDropdownMenu,
      UInput,
      UPagination,
      UPopover,
      UProgress,
      URadioGroup,
      USelect,
      USkeleton,
      USlider,
      UTable,
      UTabs,
      UCheckbox,
      UTextarea,
      UTooltip,
      USwitch,
      UModal,
    },
    nuxtUiComponentDefinitions,
  );
});
